apiVersion: v1
kind: Secret
metadata:
  name: source-controller-proxy-overlay
  namespace: tanzu-fluxcd-packageinstalls
stringData:
  add-proxy.yaml: |
    @ load("@ytt:overlay", "overlay")
    #@overlay/match by=overlay.subset({"kind": "Deployment", "metadata": {"name": "source-controller"}})
    ---
    spec:
      template:
        spec:
          #@overlay/match missing_ok=True
          containers:
            #@overlay/match by=overlay.all
            - env:
              - name: NO_PROXY
                value: 
              - name: HTTPS_PROXY
                value: 
              - name: HTTP_PROXY
                value: